include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  
  exclude:
    - '.fvm/**'
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/**/*.gql.dart"
    - "lib/generated/**/*.dart"
    - "lib/generated/*.dart"
    - "build/**"
    - "lib/**.gr.dart"
    - "lib/**.config.dart"
    - "lib/firebase_options.dart"
    - "tools/**"
    - "packages/**"
    - "test/coverage_helper_test.dart"
  
  language:
    strict-raw-types: true

  strong-mode:
    implicit-dynamic: true
  
  errors:
    invalid_annotation_target: error
    argument_type_not_assignable: error
    field_initializer_not_assignable: error
    map_value_type_not_assignable: error
    invalid_assignment: error
    return_of_invalid_type_from_closure: error
    return_of_invalid_type: error
    unnecessary_new: warning
    sort_pub_dependencies: ignore
    avoid_setters_without_getters: ignore
    import_of_legacy_library_into_null_safe: error
    avoid_single_cascade_in_expression_statements: ignore
    null_aware_in_logical_operator: error
    missing_required_param: error
    implicit_dynamic_map_literal: ignore
    prefer_single_quotes: ignore
    missing_return: error
    always_declare_return_types: error
    override_on_non_overriding_member: error
    annotate_overrides: error
    avoid_relative_lib_imports: error
    avoid_empty_else: error
    avoid_returning_null_for_future: error
    empty_statements: error
    always_put_control_body_on_new_line: error
    always_require_non_null_named_parameters: error
    avoid_renaming_method_parameters: error
    avoid_void_async: error
    parameter_assignments: error
    constant_identifier_names: error
    unawaited_futures: error
    non_constant_identifier_names: warning
    only_throw_errors: error
    exhaustive_cases: error
    always_use_package_imports: error
    missing_enum_constant_in_switch: error
    prefer_const_constructors: error
    depend_on_referenced_packages: ignore
    use_setters_to_change_properties: ignore
    avoid_classes_with_only_static_members: ignore
    avoid_positional_boolean_parameters: error
    avoid_dynamic_calls: error
    require_trailing_commas: error

linter:
  rules:

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  
  metrics:
    maximum-nesting-level: 3
    number-of-parameters: 4
    source-lines-of-code: 30
  
  metrics-exclude:
    - "test/**"
    - "widgetbook/**"
    - "**/*.gen.dart"

  rules-exclude:
    - ".fvm/**"
    - "ios/**"
    - "android/**"
    - "test/**"
    - "widgetbook/**"
    - "**/*.gen.dart"
    - "tools/**"
    - "packages/**"
  
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma:
        break-on: 3
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-type-assertions
    - no-magic-number
    - prefer-first
    - prefer-last
    - prefer-match-file-name
    - avoid-use-expanded-as-spacer
    - prefer-extracting-callbacks
    - prefer-async-await
    - prefer-moving-to-variable
    - avoid-returning-widgets
    - prefer-correct-identifier-length:
        exceptions: [ 'i' ]
        max-identifier-length: 40
        min-identifier-length: 2
    - prefer-correct-type-name:
        min-length: 2
        max-length: 40
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-methods
          - private-methods